name: self_study
description: "A Flutter project using Riverpod and FlChart."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section here:
  # assets:
  #   - assets/images/

  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
