targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/swaggers/' # Path to your schema files
          output_folder: 'lib/generated_code/' # Where generated Dart files will save
