type User @table {
  email: String!
  displayName: String!
  photoUrl: String
}

type Workspace @table {
  name: String!
  ownerId: UUID!
  description: String
  createdAt: Timestamp
}

type Task @table {
  title: String!
  status: String!
  dueDate: Timestamp
  priority: Int
  workspace: Workspace!
  parentTask: Task
  assignee: User
}

type Comment @table {
  text: String!
  task: Task!
  author: User!
  createdAt: Timestamp
}

type WorkspaceMember @table(key: ["workspace", "user"]) {
  workspace: Workspace!
  user: User!
  role: String!
  joinedAt: Timestamp
}