mutation CreateTask($title: String!, $status: String!, $workspaceId: UUID!) @auth(level: USER) {
  task_insert(
    data: {
      title: $title,
      status: $status,
      workspaceId: $workspaceId
    }
  )
}

mutation UpdateTask($id: UUID!, $status: String) @auth(level: USER) {
  task_update(
    key: { id: $id },
    data: { status: $status }
  )
}

query ListWorkspaceTasks($workspaceId: UUID!) @auth(level: USER) {
  tasks(where: { workspaceId: { eq: $workspaceId } }) {
    id
    title
    status
    dueDate
    assignee {
      displayName
    }
  }
}

mutation AddComment($taskId: UUID!, $text: String!) @auth(level: USER) {
  comment_insert(
    data: {
      taskId: $taskId,
      authorId_expr: "auth.uid",
      text: $text
    }
  )
}